### ISSUE TITLE
Create endpoints 2

### ISSUE THREAD

**Issue by theNatePi** [ctc-uci/lpa#22]
### Setup
Before you can work on the repo, you need to add the [secrets](https://docs.google.com/document/d/1qd4tsuoz3984_FcJY_Y2aT7h2A-I5IV0XkRl7ctWB2s/edit?usp=sharing).
For the Frontend .env, put it in /client.
For the Backend .env, put it in /server.

### Task
Create the following API endpoints:
```
DELETE      /events/:id
GET         /bookings/:id
GET         /bookings/event/:id
GET         /bookings/event/:id?start=[val]&end=[val]
```

For a description of each of these endpoints, see the [DB model](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=0k49t6f7gL4w5VQ6-1).
Follow proper API conventions and return [status codes ](https://restfulapi.net/http-status-codes/) along with your response. Namely 200, 404, 500, etc.

Put your endpoints into `/server/routes/[FILENAME].js`
Replace FILENAME with the name of the DB table that the endpoint is for.

Some sample files have been provided. They are in TS not JS, but you can ignore the TS stuff (and work in JS)

#### Example
GET /users/:id
Place this into `/server/routes/users.js`
See `users.ts` for the best examples.

#### Testing
To test your implementation, you can use [Postman](https://www.postman.com/downloads/) like we have in the bootcamps.

### Resources
[Secrets (.env)](https://docs.google.com/document/d/1qd4tsuoz3984_FcJY_Y2aT7h2A-I5IV0XkRl7ctWB2s/edit?usp=sharing)
[PostgreSQL DB Login](https://docs.google.com/document/d/1YQYVua-NcJgEaAJSTzEx8ftkI7paDfA5Qm9Wu12sFyo/edit?usp=sharing)
[DB Schema](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=0k49t6f7gL4w5VQ6-1)

### Checklist
- [ ] Create all endpoints
- [ ] Test all endpoints
- [ ] Commit changes
- [ ] Push changes, create PR
