### ISSUE TITLE
Create endpoints 4

### ISSUE THREAD

**Issue by jessieh9** [ctc-uci/lpa#23]
### Setup
Before you can work on the repo, you need to add the [secrets](https://docs.google.com/document/d/1qd4tsuoz3984_FcJY_Y2aT7h2A-I5IV0XkRl7ctWB2s/edit?usp=sharing).
For the Frontend .env, put it in /client.
For the Backend .env, put it in /server.

You also need to add [this file](https://drive.google.com/file/d/1A6MAix56eWFlAlcbvCXeVzwJq3emvXGD/view?usp=drive_link) in /server/config

### Task
Create the following API endpoints:
```
GET      /users/email/:email_id
GET      /users/:id
POST     /users
PUT      /users/:id
```

For a description of each of these endpoints, see the [DB model](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=0k49t6f7gL4w5VQ6-1).
Follow proper API conventions and return [status codes ](https://restfulapi.net/http-status-codes/) along with your response. Namely 200, 404, 500, etc.

Put your endpoints into `/server/routes/[FILENAME].js`
Replace FILENAME with the name of the DB table that the endpoint is for.

**Don't Forget**: use the keysToCamel function, as seen in the sample users.ts file, to make the SQL keys into camel case

Some sample files have been provided. They are in TS not JS, but you can ignore the TS stuff (and work in JS)

### Steps
1. Create file for each endpoint (users)
2. Create a router for this file (see examples)
3. Import and place this router into /server/src/App.ts (see line 40)
4. Create the functions for get/post/delete/put

#### Example
GET /users/:id
Place this into `/server/routes/users.js`
See `users.ts` for the best examples.

#### Testing
To test your implementation, you can use [Postman](https://www.postman.com/downloads/) like we have in the bootcamps.

If you put your endpoints in sample.js (for example only), then you will need to send requests to:
`127.0.0.1:3001/sample/<your endpoint>`

### Resources
[Secrets (.env)](https://docs.google.com/document/d/1qd4tsuoz3984_FcJY_Y2aT7h2A-I5IV0XkRl7ctWB2s/edit?usp=sharing)
[PostgreSQL DB Login](https://docs.google.com/document/d/1YQYVua-NcJgEaAJSTzEx8ftkI7paDfA5Qm9Wu12sFyo/edit?usp=sharing)
[DB Schema](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=0k49t6f7gL4w5VQ6-1)

### Checklist
- [x] Create all endpoints
- [x] Test all endpoints
- [x] Commit changes
- [x] Push changes, create PR
