### ISSUE TITLE
Create endpoints 5

### ISSUE THREAD

**Issue by jessieh9** [ctc-uci/lpa#25]
### Setup
Before you can work on the repo, you need to add the [secrets](https://docs.google.com/document/d/1qd4tsuoz3984_FcJY_Y2aT7h2A-I5IV0XkRl7ctWB2s/edit?usp=sharing).
For the Frontend .env, put it in /client.
For the Backend .env, put it in /server.

You also need to add [this file](https://drive.google.com/file/d/1A6MAix56eWFlAlcbvCXeVzwJq3emvXGD/view?usp=drive_link) in /server/config

### Task
Create the following API endpoints:
```
DELETE        /users/:id
GET        /comments/:id
GET        /comments/invoice/:id
GET        /comments/booking/:id
```

For a description of each of these endpoints, see the [DB model](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=0k49t6f7gL4w5VQ6-1).
Follow proper API conventions and return [status codes ](https://restfulapi.net/http-status-codes/) along with your response. Namely 200, 404, 500, etc.

Put your endpoints into `/server/routes/[FILENAME].js`
Replace FILENAME with the name of the DB table that the endpoint is for.

**Don't Forget**: use the keysToCamel function, as seen in the sample users.ts file, to make the SQL keys into camel case

Some sample files have been provided. They are in TS not JS, but you can ignore the TS stuff (and work in JS)

### Steps
1. Create file for each endpoint (users/comments)
2. Create a router for this file (see examples)
3. Import and place this router into /server/src/App.ts (see line 40)
4. Create the functions for get/post/delete/put

#### Example
GET /users/:id
Place this into `/server/routes/users.js`
See `users.ts` for the best examples.

#### Testing
To test your implementation, you can use [Postman](https://www.postman.com/downloads/) like we have in the bootcamps.

If you put your endpoints in sample.js (for example only), then you will need to send requests to:
`127.0.0.1:3001/sample/<your endpoint>`

### Resources
[Secrets (.env)](https://docs.google.com/document/d/1qd4tsuoz3984_FcJY_Y2aT7h2A-I5IV0XkRl7ctWB2s/edit?usp=sharing)
[PostgreSQL DB Login](https://docs.google.com/document/d/1YQYVua-NcJgEaAJSTzEx8ftkI7paDfA5Qm9Wu12sFyo/edit?usp=sharing)
[DB Schema](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=0k49t6f7gL4w5VQ6-1)

### Checklist
- [x] Create all endpoints
- [x] Test all endpoints
- [x] Commit changes
- [x] Push changes, create PR

**Comment by theNatePi** [comment]
Good work guys, just a few notes. Don't worry about these too much as we will go over them at the sprint meeting tomorrow!

Make sure to pull again, I commented out unused "user" endpoints to help keep things clean and simple.

Todo:
- [ ] Fix "DELETE /users/:id"
    - Fix the endpoint to just `/:id`, not `/users/:id`. The "users" part is already handled by the router.
    - Double check the return value in the DB model [here](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=KBJC0nAjareGL7W8-1). This endpoint should return `{“result”: “success” / “error”}`. You can use `DELETE FROM bookings WHERE id = $1 RETURNING *`. Then you could check the return value from RETURNING. If a row was deleted, the data from that row would be returned
- [ ] Fix comments router
    - Add an export for the commentsRouter in the comments.ts file
    - Import the commentsRouter in the app.ts
    - Add the router with app.use at the bottom of app.ts
