### ISSUE TITLE
Create Rooms and Events Tables

### ISSUE THREAD

**Issue by theNatePi** [ctc-uci/lpa#9]
### Setup
1. Clone this repository to your local machine
2. On the right side of this issue, create a new branch
    - Check the right side of the GitHub UI
4. Use the commands provided to switch to that branch before you begin working
    - The commands will pop up once you make the branch
 
### IMPORTANT
- We are using Yarn. NEVER `npm install`, always use Yarn
- BEFORE you commit, use `git add <names of files>`. ONLY add files you modified, including the yarn.lock if you added new modules
- BEFORE you commit, use `git status`. Ensure files you changed are in green, irrelevant files are in red
- Make sure you always push to your new branch, never push to main
- See the bottom of this doc for resources on Git if you are lost, and feel free to reach out to Nate and Jessie at any time!

NOTE:
We are using PostgreSQL, not just SQL. Be sure to include Postgres when searching for documentation.
For time/datetime types, see this documentation: [link](https://www.postgresql.org/docs/current/datatype-datetime.html)
 
### Task
1. Implement the rooms and events tables (found in the DB model linked below)
    - A template has been created for you on [this website](https://www.db-fiddle.com/f/7T1Xqo5RTtdcnJuhmCziqJ/3)
    - This template will let you implement and test your tables
6. When done on the DB Fiddle, create a new file called rooms.sql, and another one called events.sql in [/lpa/server/db/schema/](https://github.com/ctc-uci/lpa/tree/main/server/db/schema)
    - Do this locally in VS code or your files, do not do this on the GitHub website
    - The GitHub desktop client is not recommended, it is a good skill to learn the command line!
7. Put the create statement for rooms and events in those files. **DO NOT** put any of the other template SQL or comments
8. Commit and push these changes to GitHub
9. Create a PR describing the changes you made
 
### Pre-submit checklist
 
- [x] The rooms and events tables on DB fiddle runs without errors
- [x] The provided insert statements run
- [x] I have written more insert statements to test unique constraints and defaults
- [x] Changes are committed to a new branch for this issue (don't commit to MAIN!!)
- [x] These changes are pushed to the remote repo
 
Now, create the PR!

Please complete before November 30th
 
### Resources
- [DB Model](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=TGkEF5yuSn0A22uy-1)
- [Git Resources](https://docs.google.com/document/d/1OyQ8u6m2O1nJBdzLMHGkpZUbd3FYyrhRcT7Y4Qr6UxA/edit?tab=t.0#heading=h.ss1h6pz82xhv)
